import Cards from '@/components/Cards'
import Chart from '@/components/Chart'
import RecentOrder from '@/components/RecentOrder'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'




export default function Home() {
  return (
    <>
      <Head>
        <title>Admin | Prathamesh Patil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <Cards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <Chart />
          <RecentOrder />
        </div>
      </main>
      
    </>
  )
}
